spring:
  application:
    name: youth-policy-mate
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    clean-disabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    enabled: false
