spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

server:
  forward-headers-strategy: framework

management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState,db

APP_FRONTEND_URL: ${PUBLIC_APP_URL}
APP_BACKEND_URL: ${PUBLIC_APP_URL}
APP_COOKIE_SECURE: true
